version: '3.7'

services: 
  db:
    image: mysql:8.0.15
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
    volumes:
      - rails-rspec-capybara-usage-db:/var/lib/mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
  app:
    tty: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: rails server -b 0.0.0.0
volumes:
  rails-rspec-capybara-usage-db:
